<?php
declare(strict_types=1);

/**
 * TourSync — the signed-in user's own profile and password.
 *
 * Separate from the accounts screen on purpose: changing your own password is
 * something every user must be able to do, while creating and disabling
 * accounts belongs to the Tourism Officer alone.
 */

require_once __DIR__ . '/../../bootstrap.php';

use App\Core\ActivityLog;
use App\Core\Auth;
use App\Core\Csrf;
use App\Core\Session;
use App\Core\Validator;
use App\Repositories\AdminRepository;

Auth::require();

$pageTitle    = 'My Account';
$pageIcon     = 'fa-user-gear';
$pageSubtitle = 'Your profile and password';

$id = (int) Auth::id();
$me = AdminRepository::find($id);

if (is_post()) {
    Csrf::verify();
    $action = (string) ($_POST['action'] ?? '');

    // ---- Profile ----------------------------------------------------------
    if ($action === 'profile') {
        $v = new Validator($_POST);
        $v->require('full_name', 'email')->length('full_name', 2, 120)->email('email');

        if ($v->passes() && AdminRepository::emailTaken((string) $v->value('email'), $id)) {
            $v->addError('email', 'Another account already uses that email address.');
        }

        if ($v->fails()) {
            flash_back($v->errors(), $_POST, 'index.php');
        }

        AdminRepository::updateProfile($id, [
            'full_name' => (string) $v->value('full_name'),
            'email'     => (string) $v->value('email'),
        ]);

        // The name is shown in the topbar from the session, so refresh it.
        $_SESSION['_admin']['full_name'] = (string) $v->value('full_name');

        ActivityLog::record('account.profile', 'admin', $id, 'Updated own profile');
        Session::flash('success', 'Profile updated.');
        redirect(base_url('/admin/account/index.php'));
    }

    // ---- Password ---------------------------------------------------------
    if ($action === 'password') {
        $current = (string) ($_POST['current_password'] ?? '');
        $new     = (string) ($_POST['new_password'] ?? '');
        $confirm = (string) ($_POST['confirm_password'] ?? '');

        $errors = [];

        // The current password is required even though the session already
        // proves identity: it stops an unattended, still-signed-in terminal
        // being used to take the account over permanently.
        if (!password_verify($current, $me['password_hash'])) {
            $errors['current_password'] = 'That is not your current password.';
        }

        $problems = AdminRepository::passwordProblems($new);
        if ($problems !== []) {
            $errors['new_password'] = 'The new password ' . implode(', and ', $problems) . '.';
        }

        if ($new !== $confirm) {
            $errors['confirm_password'] = 'The two entries do not match.';
        }

        if ($new === $current && !isset($errors['current_password'])) {
            $errors['new_password'] = 'The new password must be different from the current one.';
        }

        if ($errors !== []) {
            flash_back($errors, [], 'index.php');
        }

        AdminRepository::changePassword($id, $new);
        ActivityLog::record('account.password', 'admin', $id, 'Changed own password');

        Session::flash('success', 'Password changed. It takes effect on your next sign-in.');
        redirect(base_url('/admin/account/index.php'));
    }
}

$neverChanged = $me['password_changed_at'] === null;

require __DIR__ . '/../_partials/head.php';
?>

<?php if ($neverChanged): ?>
    <div class="alert alert-warning">
        <i class="fa-solid fa-triangle-exclamation"></i>
        <strong>This account is still using the password generated by the installer.</strong>
        That password was printed to a terminal and may exist in a screenshot, a chat log, or a
        notebook. Change it below.
    </div>
<?php endif; ?>

<div class="panel-row">
    <div>
        <section class="panel">
            <header class="panel__head"><h2><i class="fa-solid fa-key"></i> Change Password</h2></header>
            <div class="panel__body">
                <form method="post" class="row g-3" novalidate autocomplete="off">
                    <?= csrf_field() ?>
                    <input type="hidden" name="action" value="password">

                    <div class="col-12">
                        <label for="current_password" class="form-label">Current password <span class="req">*</span></label>
                        <input type="password" id="current_password" name="current_password" required
                               autocomplete="current-password"
                               class="form-control <?= has_error('current_password') ? 'is-invalid' : '' ?>">
                        <?php if (has_error('current_password')): ?>
                            <div class="field-error"><?= e(error_for('current_password')) ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="col-md-6">
                        <label for="new_password" class="form-label">New password <span class="req">*</span></label>
                        <input type="password" id="new_password" name="new_password" required
                               autocomplete="new-password"
                               class="form-control <?= has_error('new_password') ? 'is-invalid' : '' ?>">
                        <p class="field-hint">At least 10 characters, with a letter and a number.</p>
                        <?php if (has_error('new_password')): ?>
                            <div class="field-error"><?= e(error_for('new_password')) ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="col-md-6">
                        <label for="confirm_password" class="form-label">Confirm new password <span class="req">*</span></label>
                        <input type="password" id="confirm_password" name="confirm_password" required
                               autocomplete="new-password"
                               class="form-control <?= has_error('confirm_password') ? 'is-invalid' : '' ?>">
                        <?php if (has_error('confirm_password')): ?>
                            <div class="field-error"><?= e(error_for('confirm_password')) ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="col-12">
                        <button type="submit" class="btn btn-brand">
                            <i class="fa-solid fa-key"></i> Change Password
                        </button>
                    </div>
                </form>
            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h2><i class="fa-regular fa-user"></i> Profile</h2></header>
            <div class="panel__body">
                <form method="post" class="row g-3" novalidate>
                    <?= csrf_field() ?>
                    <input type="hidden" name="action" value="profile">

                    <div class="col-md-6">
                        <label for="full_name" class="form-label">Full name <span class="req">*</span></label>
                        <input type="text" id="full_name" name="full_name" required maxlength="120"
                               class="form-control <?= has_error('full_name') ? 'is-invalid' : '' ?>"
                               value="<?= old('full_name', $me['full_name']) ?>">
                        <?php if (has_error('full_name')): ?>
                            <div class="field-error"><?= e(error_for('full_name')) ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="col-md-6">
                        <label for="email" class="form-label">Email <span class="req">*</span></label>
                        <input type="email" id="email" name="email" required maxlength="160"
                               class="form-control <?= has_error('email') ? 'is-invalid' : '' ?>"
                               value="<?= old('email', $me['email']) ?>">
                        <?php if (has_error('email')): ?>
                            <div class="field-error"><?= e(error_for('email')) ?></div>
                        <?php endif; ?>
                    </div>

                    <div class="col-12">
                        <button type="submit" class="btn btn-outline-secondary">
                            <i class="fa-solid fa-floppy-disk"></i> Save Profile
                        </button>
                    </div>
                </form>
            </div>
        </section>
    </div>

    <div class="panel-stack">
        <section class="panel">
            <header class="panel__head"><h2><i class="fa-solid fa-id-card"></i> Account</h2></header>
            <div class="panel__body">
                <dl class="detail-grid detail-grid--single">
                    <div><dt>Username</dt><dd class="mono"><?= e($me['username']) ?></dd></div>
                    <div><dt>Role</dt><dd><?= $me['role'] === 'officer' ? 'Tourism Officer' : 'Tourism Staff' ?></dd></div>
                    <div><dt>Last sign-in</dt><dd><?= $me['last_login_at'] ? e(format_date($me['last_login_at'], 'M j, Y g:i A')) : 'This is your first' ?></dd></div>
                    <div>
                        <dt>Password last changed</dt>
                        <dd class="<?= $neverChanged ? 'text-danger' : '' ?>">
                            <?= $neverChanged ? 'Never — still the installer password' : e(format_date($me['password_changed_at'], 'M j, Y')) ?>
                        </dd>
                    </div>
                    <div><dt>Account created</dt><dd><?= e(format_date($me['created_at'])) ?></dd></div>
                </dl>
            </div>
        </section>

        <section class="panel">
            <header class="panel__head"><h2><i class="fa-solid fa-shield-halved"></i> Security Notes</h2></header>
            <div class="panel__body">
                <ul class="lb-list" style="display:grid;gap:.6rem;list-style:none;padding:0;margin:0;font-size:.84rem;color:var(--ink-2)">
                    <li><i class="fa-solid fa-lock" style="color:var(--green);margin-right:.5rem"></i>
                        Passwords are stored as Argon2id hashes and cannot be read by anyone, including this office.</li>
                    <li><i class="fa-solid fa-ban" style="color:var(--green);margin-right:.5rem"></i>
                        Five failed sign-ins lock the account for fifteen minutes.</li>
                    <li><i class="fa-solid fa-clock" style="color:var(--green);margin-right:.5rem"></i>
                        Sessions end after 30 minutes idle, or 8 hours regardless.</li>
                    <li><i class="fa-solid fa-clipboard-list" style="color:var(--green);margin-right:.5rem"></i>
                        Every sign-in and administrative change is recorded in the activity log.</li>
                </ul>
            </div>
        </section>
    </div>
</div>

<?php require __DIR__ . '/../_partials/foot.php'; ?>
