/* =============================================================================
   TourSync — service worker                                       Feature 2
   -----------------------------------------------------------------------------
   Two jobs, and only two.

   1. Keep the logbook openable with no signal. A tourist who scanned a sign at
      a waterfall and then walked out of coverage should still see the form,
      not a dinosaur.

   2. Send what the phone is holding, after the browser has been closed. This
      is the half a page script cannot do: Background Sync wakes this worker
      when the network returns, whether or not anybody has the site open.

   It deliberately does NOT cache API responses or intercept POSTs. An arrival
   is written through the queue in arrival-queue.js, which owns that path
   entirely — two mechanisms racing to deliver the same record is how a visit
   gets counted twice.
   ========================================================================== */

'use strict';

var VERSION = 'toursync-v1';
var SHELL   = VERSION + '-shell';
var RUNTIME = VERSION + '-runtime';

/* The worker is registered at the application root, so its scope is the app —
   and every path below can be resolved against it. This is what lets the same
   file work at / and at /TampakanTourism/ without being generated by PHP. */
var BASE = self.registration.scope;

var SHELL_URLS = [
    'offline.html',
    'assets/css/logbook.css',
    'assets/js/arrival-queue.js',
    'assets/img/tampakan_logo.png'
].map(function (path) { return new URL(path, BASE).toString(); });

importScripts(new URL('assets/js/arrival-queue.js', BASE).toString());

ArrivalQueue.configure({
    submitUrl: new URL('api/arrivals/submit.php', BASE).toString(),
    tokenUrl:  new URL('api/arrivals/token.php', BASE).toString()
});

/* ---- Install ------------------------------------------------------------ */

self.addEventListener('install', function (event) {
    event.waitUntil(
        caches.open(SHELL).then(function (cache) {
            /* addAll is all-or-nothing: one 404 and the whole worker fails to
               install, silently taking offline support with it. Each file is
               added on its own so a missing asset costs only that asset. */
            return Promise.all(SHELL_URLS.map(function (url) {
                return cache.add(url).catch(function () { /* keep going */ });
            }));
        }).then(function () {
            return self.skipWaiting();
        })
    );
});

/* ---- Activate ----------------------------------------------------------- */

self.addEventListener('activate', function (event) {
    event.waitUntil(
        caches.keys().then(function (names) {
            return Promise.all(names.map(function (name) {
                if (name !== SHELL && name !== RUNTIME) {
                    return caches.delete(name);
                }
            }));
        }).then(function () {
            return self.clients.claim();
        })
    );
});

/* ---- Fetch -------------------------------------------------------------- */

self.addEventListener('fetch', function (event) {
    var request = event.request;

    /* Submissions are the queue's business, not the cache's. */
    if (request.method !== 'GET') {
        return;
    }

    var url = new URL(request.url);

    /* Never serve an API read from cache — a stale destination list or a stale
       CSRF token is worse than an honest failure. */
    if (url.pathname.indexOf('/api/') !== -1) {
        return;
    }

    /* Pages: network first, because a logbook form carries a CSRF token and a
       render timestamp that should be as fresh as the connection allows. The
       cache is the safety net, and offline.html is the net under that. */
    if (request.mode === 'navigate') {
        event.respondWith(
            fetch(request).then(function (response) {
                var copy = response.clone();
                caches.open(RUNTIME).then(function (cache) { cache.put(request, copy); });
                return response;
            }).catch(function () {
                return caches.match(request).then(function (cached) {
                    return cached || caches.match(new URL('offline.html', BASE).toString());
                });
            })
        );
        return;
    }

    /* Everything else — stylesheets, scripts, the seal, the CDN icon font.
       Serve from cache immediately and refresh in the background, so a second
       visit with no signal still looks like the site. */
    event.respondWith(
        caches.match(request).then(function (cached) {
            var network = fetch(request).then(function (response) {
                if (response && (response.ok || response.type === 'opaque')) {
                    var copy = response.clone();
                    caches.open(RUNTIME).then(function (cache) { cache.put(request, copy); });
                }
                return response;
            }).catch(function () {
                return cached;
            });

            return cached || network;
        })
    );
});

/* ---- Background Sync ----------------------------------------------------
   The part that makes the claim true. The browser fires this when it believes
   connectivity is back — potentially long after the tab was closed — and will
   fire it again later if the promise rejects. Rejecting on "work remaining" is
   therefore not an error path, it is how a retry is requested. */

self.addEventListener('sync', function (event) {
    if (event.tag === 'sync-arrivals') {
        event.waitUntil(
            ArrivalQueue.drain().then(function (report) {
                notifyClients(report);

                if (report.remaining > 0) {
                    throw new Error('arrivals still queued — retry');
                }
            })
        );
    }
});

/* Safari and Firefox do not implement Background Sync. There the page asks
   directly, through this channel, whenever it notices the network return. */
self.addEventListener('message', function (event) {
    if (!event.data || event.data.type !== 'drain-arrivals') {
        return;
    }

    event.waitUntil(
        ArrivalQueue.drain().then(notifyClients)
    );
});

function notifyClients(report) {
    return self.clients.matchAll({ includeUncontrolled: true }).then(function (clients) {
        clients.forEach(function (client) {
            client.postMessage({ type: 'arrivals-synced', report: report });
        });
    });
}
